services:
  api:
    build: .
    depends_on:
      - database
    links:
      - database
    ports:
      - "80:80"
  database:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gooooo
      MYSQL_USER: martin
      MYSQL_PASSWORD: martin
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database_data:/var/lib/mysql

volumes:
  database_data: