services:
  api:
    build: .
    depends_on:
      - database
    links:
      - database
    ports:
      - "8080:80"
  database:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:${MYSQL_TCP_PORT}"
